title: "Leonel Alejandro García López"
author: "Leonel Alejandro García López"
email: "lagcleaner@gmail.com"
description: "Data Engineer | DevOps Enthusiast | Backend & Mobile Developer | Probably Debugging Right Now"
github_username: "lagcleaner"
theme: jekyll-theme-minimal
show_downloads: false
