title: "Leonel Alejandro García López"
author: "Leonel Alejandro García López"
email: "lagcleaner@gmail.com"
description: "Backend & Mobile Development | DevOps | Data Engineer | Probably Debugging Right Now"
github_username: "lagcleaner"
theme: jekyll-theme-minimal
show_downloads: false
include: ["assets/css/style.css"]
